export const mockUsers = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@restaurant.com",
    password: "admin123",
    role: "ADMIN",
    isActive: true,
  },
  {
    id: "2",
    name: "John Cashier",
    email: "cashier@restaurant.com",
    password: "cashier123",
    role: "CASHIER",
    isActive: true,
  },
  {
    id: "3",
    name: "Sarah Waiter",
    email: "waiter@restaurant.com",
    password: "waiter123",
    role: "WAITER",
    isActive: true,
  },
  {
    id: "4",
    name: "Mike Kitchen",
    email: "kitchen@restaurant.com",
    password: "kitchen123",
    role: "KITCHEN",
    isActive: true,
  },
];

export const mockCategories = [
  { id: "1", name: "Appetizers" },
  { id: "2", name: "Main Course" },
  { id: "3", name: "Desserts" },
  { id: "4", name: "Beverages" },
];

export const mockMenuItems = [
  {
    id: "1",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with parmesan and croutons",
    price: 8.99,
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "1",
  },
  {
    id: "2",
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter",
    price: 5.99,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "1",
  },
  {
    id: "3",
    name: "Grilled Salmon",
    description: "Fresh Atlantic salmon with herbs",
    price: 24.99,
    imageUrl: "https://images.unsplash.com/photo-1467003904429-263fb42d7f42?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: false,
    categoryId: "2",
  },
  {
    id: "4",
    name: "Beef Steak",
    description: "Prime beef cooked to perfection",
    price: 29.99,
    imageUrl: "https://images.unsplash.com/photo-1600891964599-f61f63b1c5c8?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: false,
    categoryId: "2",
  },
  {
    id: "5",
    name: "Pasta Primavera",
    description: "Fresh vegetables with penne pasta",
    price: 16.99,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc44ae8f3?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "2",
  },
  {
    id: "6",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center",
    price: 7.99,
    imageUrl: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "3",
  },
  {
    id: "7",
    name: "Tiramisu",
    description: "Classic Italian dessert",
    price: 8.99,
    imageUrl: "https://images.unsplash.com/photo-1571877223353-3f490a49f2b0?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "3",
  },
  {
    id: "8",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 4.99,
    imageUrl: "https://images.unsplash.com/photo-1600271886742-f04967a4c3a9?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "4",
  },
  {
    id: "9",
    name: "Espresso",
    description: "Strong Italian coffee",
    price: 3.99,
    imageUrl: "https://images.unsplash.com/photo-1517959105821-eaf2591984ca?w=600&h=400&fit=crop",
    isAvailable: true,
    isVeg: true,
    categoryId: "4",
  },
];

export const mockTables = [
  { id: "1", tableNumber: 1, seats: 4, status: "AVAILABLE", assignedTo: null },
  { id: "2", tableNumber: 2, seats: 2, status: "OCCUPIED", assignedTo: "3" },
  { id: "3", tableNumber: 3, seats: 6, status: "RESERVED", assignedTo: "3" },
  { id: "4", tableNumber: 4, seats: 4, status: "AVAILABLE", assignedTo: null },
  { id: "5", tableNumber: 5, seats: 2, status: "OCCUPIED", assignedTo: "3" },
  { id: "6", tableNumber: 6, seats: 8, status: "NEEDS_CLEANING", assignedTo: null },
  { id: "7", tableNumber: 7, seats: 4, status: "AVAILABLE", assignedTo: null },
  { id: "8", tableNumber: 8, seats: 2, status: "AVAILABLE", assignedTo: null },
];

export const mockOrders = [
  {
    id: "1",
    tableNumber: 2,
    status: "PREPARING",
    total: 59.96,
  },
  {
    id: "2",
    tableNumber: 5,
    status: "READY",
    total: 38.98,
  },
  {
    id: "3",
    tableNumber: 2,
    status: "PENDING",
    total: 74.94,
  },
];
export const mockReservations = [
  {
    id: "1",
    tableId: "3",
    guestName: "John Smith",
    guestPhone: "+1-555-0123",
    guests: 4,
    reservedAt: new Date("2025-01-15T19:00:00"),
    reservedUntil: new Date("2025-01-15T21:00:00"),
    durationMin: 120,
    status: "ACTIVE",
  },
  {
    id: "2",
    tableId: "6",
    guestName: "Emma Wilson",
    guestPhone: "+1-555-0456",
    guests: 8,
    reservedAt: new Date("2025-01-15T20:00:00"),
    reservedUntil: new Date("2025-01-15T22:00:00"),
    durationMin: 120,
    status: "ACTIVE",
  },
];
export const mockBills = [
  {
    id: "1",
    orderId: "2",
    generatedAt: new Date("2025-01-15T13:45:00"),
    subTotal: 38.98,
    discountValue: 5,
    discountType: "PERCENTAGE",
    serviceCharge: 2.0,
    taxPct: 13,
    taxAmount: 4.68,
    grandTotal: 43.61,
    paymentMode: "CARD",
    isPaid: true,
    paidAt: new Date("2025-01-15T13:46:00"),
  },
];
