export const AUTH_AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  LOGOUT: 'AUTH_LOGOUT',
  REFRESH_SESSION: 'AUTH_REFRESH_SESSION',
  REFRESH_FAILURE: 'AUTH_REFRESH_FAILURE',
  ACCOUNT_CREATED: 'AUTH_ACCOUNT_CREATED',
  PASSWORD_RESET_REQUEST: 'AUTH_PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS: 'AUTH_PASSWORD_RESET_SUCCESS',
  ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  SUSPICIOUS_ACTIVITY: 'AUTH_SUSPICIOUS_ACTIVITY', 
} as const;