export const MENU_ITEM_AUDIT_ACTIONS = {
  CREATED: 'MENU_ITEM_CREATED',
  UPDATED: 'MENU_ITEM_UPDATED',
  DELETED: 'MENU_ITEM_DELETED',
  RESTORED: 'MENU_ITEM_RESTORED',
  AVAILABILITY_CHANGED: 'MENU_ITEM_AVAILABILITY_CHANGED',
  PRICE_UPDATED: 'MENU_ITEM_PRICE_UPDATED',
  SUSPICIOUS_CHANGE: 'MENU_ITEM_SUSPICIOUS_CHANGE',
} as const;   