export const TABLE_AUDIT_ACTIONS = {
  TABLE_CREATED: 'TABLE_CREATED',
  TABLE_DELETED: 'TABLE_DELETED',
  TABLE_RESTORED: 'TABLE_RESTORED',
  TABLE_UPDATED_NAME: 'TABLE_UPDATED_NAME',
  TABLE_UPDATED_SEATS: 'TABLE_UPDATED_SEATS',
  TABLE_STATUS_CHANGED: 'TABLE_STATUS_CHANGED',
  TABLE_ASSIGNED_WAITER: 'TABLE_ASSIGNED_WAITER',
  TABLE_UNASSIGNED_WAITER: 'TABLE_UNASSIGNED_WAITER',
  TABLE_OCCUPIED: 'TABLE_OCCUPIED',
  TABLE_UPDATED: 'TABLE_UPDATED',
  TABLE_CLEANING_STARTED: 'TABLE_CLEANING_STARTED',
  TABLE_AVAILABLE: 'TABLE_AVAILABLE',
} as const;